### ISSUE TITLE
Fail build if MsBuild fails

### ISSUE THREAD

**Issue by iskiselev** [daveaglick/Scripty#37] opened 2016-07-26 02:29 UTC
If processed script ended with exception, MsBuild project build should receive error message and also fail.
Now it wrote error message in console output, but it has no affect on later build.

**Comment by daveaglick** [comment] 2017-04-07 18:55
This should be resolved in the next release, 0.7.2

**Closed as completed by daveaglick** 2017-04-07 18:55 UTC
Labels: Bug

**Comment by TylerBrinkley** [comment] 2017-04-07 19:21
Hmm, while I appreciate the need for this, failing the build will actually cause an issue for us.

The problem is that we use Scripty to generate json configuration files which are automatically copied to the bin folder upon compilation. Below is our scenario.

| | Assembly.dll | AssemblyConfig.dll |
| --- | --- | --- |
| Dependencies | - | Assembly.dll |
| Files | Config.csx => AssemblyConfig.GenerateConfig | GenerateConfig.cs |

AssemblyConfig.dll is dependent on Assembly.dll but the Assembly.dll project contains the Config.csx so that its output is copied to the bin folder but it calls into the AssemblyConfig.dll. Since Scripty.MSBuild runs before build AssemblyConfig.dll may not exist and thus Scripty will fail but I don't want Assembly.dll to fail to build as it's required in order for AssemblyConfig.dll to build. What we do is build the solution twice and then we're guaranteed both assemblies will have been built and the config will be generated with the latest settings.

Failing the build will unfortunately prevent this scenario. I understand that for many scenarios failing the build is the right thing to do so I ask could an option be added to disable failing the build within the csproj or perhaps in a scripty.msbuild.config file?

**Comment by TylerBrinkley** [comment] 2017-04-07 19:29
We used to use the Custom Tool to avoid these issues but we switched to using the MSBuild NuGet package as it's convenient that it runs on each build and due to the inconvenience of having to close Visual Studio all the time due to #72. We may switch back if an option to disable failing the build cannot be added.

**Comment by daveaglick** [comment] 2017-04-07 19:29
Yep, can add an option - you were about 5 minutes too late though and I just pushed 0.7.2 to NuGet. I'll get an option in place and then publish one more release.

**Comment by TylerBrinkley** [comment] 2017-04-07 19:31
That'd be great, thanks! We can stick with 0.6.0 until you have another reason to push another update out so no rush.

**Comment by daveaglick** [comment] 2017-04-07 19:33
The way I tend to jump in and out of this project, who knows when I'll be back again :wink:

**Comment by daveaglick** [comment] 2017-04-07 20:18
Okay, commit going in now - you'll be able to add this to your project file:
```
<PropertyGroup>
  <ScriptyContinueOnError>true</ScriptyContinueOnError>
</PropertyGroup>
```
